In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df=sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [5]:
df.shape

(344, 7)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [6]:
# calculating null values

df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [7]:
# drop null values

df.dropna(inplace=True)

In [10]:
#checking dataset

df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [ ]:
#Future Engineerning , One hot Encoding categorical data into numeric

In [11]:
df.sex.unique()

array(['Male', 'Female'], dtype=object)

In [12]:
pd.get_dummies(df['sex'].head())   #converting them into 0 or 1 into dataframes

Female  Male
0       0     1
1       1     0
2       1     0
4       1     0
5       0     1

In [13]:
sex=pd.get_dummies(df['sex'],drop_first=True)
sex.head()

Male
0     1
1     0
2     0
4     0
5     1

In [14]:
# we have dropped the first cloumn as it is enough to determine the penguins gender


In [16]:
##Applying one-hot encoding to island

In [17]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [21]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [22]:
island=pd.get_dummies(df['island'],drop_first=True)
island.head(5)

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [ ]:
#concatenate the above two datafranes to main dataframe

In [23]:
new_data=pd.concat([df,island,sex],axis=1)

In [24]:
new_data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Dream  Torgersen  Male  
0       3750.0    Male      0          1     1  
1       3800.0  Female      0          1     0  
2       3250.0  Female      0          1     0  
4       3450.0  Female      0          1     0  
5       3650.0    Male      0          1     1

In [25]:
new_data.drop(['sex','island'],axis=1,inplace=True)

In [26]:
new_data.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Dream  Torgersen  Male  
0      0          1     1  
1      0          1     0  
2      0          1     0  
4      0          1     0  
5      0          1     1

In [27]:
## creating seperate target varible

In [28]:
Y=new_data.species

Y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [29]:
Y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [30]:
Y=Y.map({'Adelie':0,'Chinstrap':1,'Gentoo':2})  #hot encoding
Y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [ ]:
#dropping the target varible :Species

In [31]:
new_data.drop('species',inplace=True,axis=1)

In [32]:
new_data.head()

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
0            39.1           18.7              181.0       3750.0      0   
1            39.5           17.4              186.0       3800.0      0   
2            40.3           18.0              195.0       3250.0      0   
4            36.7           19.3              193.0       3450.0      0   
5            39.3           20.6              190.0       3650.0      0   

   Torgersen  Male  
0          1     1  
1          1     0  
2          1     0  
4          1     0  
5          1     1

In [33]:
X=new_data

In [34]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=0)

In [35]:
print('x_train',X_train.shape)
print('x_test',X_test.shape)
print('Y_train',y_train.shape)
print('y_test',y_test.shape)

x_train (233, 7)
x_test (100, 7)
Y_train (233,)
y_test (100,)


In [36]:
# training Random forest Classification on tarining set

In [38]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [39]:
##predicting test results

In [40]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2, 1, 2, 1, 0,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 2], dtype=int64)

In [42]:
#Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report,accuracy_score

In [44]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[48  0  0]
 [ 2 14  0]
 [ 0  0 36]]


In [45]:
accuracy_score(y_test,y_pred)

0.98

In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        48
           1       1.00      0.88      0.93        16
           2       1.00      1.00      1.00        36

    accuracy                           0.98       100
   macro avg       0.99      0.96      0.97       100
weighted avg       0.98      0.98      0.98       100



In [47]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=7,criterion='gini',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [48]:
y_pred=classifier.predict(X_test)

In [49]:
accuracy_score(y_test,y_pred)

0.99

In [ ]:
#more trees more accuracy